platform :ios, '9.0'

target 'GRPCClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GRPCClient
  pod 'SwiftGRPC'

  target 'GRPCClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
